@address=localhost:8000

### create provider type
POST http://{{address}}/provider_type
Content-Type: application/json

{
    "name": "provider-type-01",
	"state": "active",
	"description": "description-01"
}

### query provider type
GET  http://{{address}}/provider_type
Content-Type: application/json

{
    "id": "c560662a-cd8c-4f01-b0d8-1ec4bf7ce7fb"
}

### create provider
POST http://{{address}}/provider
Content-Type: application/json

{
    "name": "provider-01",
	"url": "url-01",
	"state": "active",
	"provider_type": "c560662a-cd8c-4f01-b0d8-1ec4bf7ce7fb",
	"description": "description-01"
}

### query provider
GET  http://{{address}}/provider
Content-Type: application/json

{
    "id": "4872cc16-2799-49a0-9cb6-035cc60c2029"
}

### create policy
POST http://{{address}}/policy
Content-Type: application/json

{
    "name": "policy-test-01",
	"state": "active",
	"provider": "1eda8c17-06c4-4113-8102-384b0a48e005",
	"resource_type": "resource-type-test-01",
	"resources_evaluated": "resources-evaluated-test-01",
	"tags": "705e4dcb-3ecd-24f3-3a35-3e926e4bded5",
	"steampipe": "steampipe-01"
}

### delete policy
DELETE http://{{address}}/policy
Content-Type: application/json

{
    "name": "policy-test-01"
}

### update policy
PUT  http://{{address}}/policy
Content-Type: application/json

{
    "name": "policy-test-01",
	"state": "active",
	"provider": "1eda8c17-06c4-4113-8102-384b0a48e005",
	"resource_type": "resource-type-test-update",
	"resources_evaluated": "resources-evaluated-test-update",
	"tags": "705e4dcb-3ecd-24f3-3a35-3e926e4bded5",
	"steampipe": "steampipe-update"
}

### query policy
GET  http://{{address}}/policy
Content-Type: application/json

{
    "name": "policy-test-01"
}

### create tag
POST http://{{address}}/tags
Content-Type: application/json

{
	"state": "active",
	"provider": "1eda8c17-06c4-4113-8102-384b0a48e005",
	"type": "type-01",
	"key": "key-01",
	"value": "value-01"
}

### query tags
GET  http://{{address}}/tags
Content-Type: application/json

{
    "type": "type-01",
	"key": "key-01"
}