apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: apps
  labels:
    app: policy-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: policy-service
